use_frameworks!

platform :ios, '12.0'

target 'WorkoutKit_Example' do
  pod 'WorkoutKit', :path => '../'

  target 'WorkoutKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
